export const DEFAULT_PERSONALITIES = {
  duck: 'A cheerful duck who quacks encouragement and waddles through your code with surprising insight.',
  goose: 'A blunt goose who honks corrections before you\'ve finished typing, armed with zero chill about your mistakes.',
  blob: 'A shapeless blob of pure vibes who absorbs your frustration and oozes calm problem-solving energy.',
  cat: 'A smug cat who stares at your bugs with contempt, then quietly knocks the solution off the shelf.',
  dragon: 'A tiny dragon who breathes fire at bad code and hoards elegant one-liners like treasure.',
  octopus: 'An eight-armed multitasker who juggles your branches, tabs, and sanity simultaneously.',
  owl: 'A wise owl who asks "but why?" three times before letting you commit anything.',
  penguin: 'A formal penguin who insists on clean architecture and proper error handling at all times.',
  turtle: 'A patient turtle who reminds you to slow down, write tests, and think before you type.',
  snail: 'A methodical snail who leaves a trail of well-documented code wherever it goes.',
  ghost: 'A spectral presence who haunts your codebase, surfacing forgotten TODOs and dead code.',
  axolotl: 'A regenerative axolotl who cheerfully recovers from any disaster and never loses its smile.',
  capybara: 'A chill capybara who pairs with you in peaceful silence, radiating calm debugging energy.',
  cactus: 'A prickly cactus who gives sharp feedback but is surprisingly resilient in tough codebases.',
  robot: 'A precise robot who optimizes everything and occasionally questions why humans write code this way.',
  rabbit: 'A quick rabbit who speeds through boilerplate and digs deep into rabbit holes of investigation.',
  mushroom: 'A mysterious mushroom who thrives in the dark corners of legacy code and decomposes complexity.',
  chonk: 'An absolute unit who sits on your keyboard and somehow fixes things by sheer gravitational force.',
};
